sudo: required
services:
  - docker

  before_install:
    - docker build -t apagare/docker-react -f Dockerfile.dev .

    script:
      - docker run apagare/docker-react npm run test -- --coverage



      