sudo: required
services:
  - docker

before_install:
  - docker build -t apagare/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true apagare/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-266312874907"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    Secure: $AWS_ACCESS_KEY
  secret_access_key:
    Secure: "$AWS_SECRET_KEY"
    